apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:latest
        ports:
        - containerPort: 80
        args:
          - --no-auth
        volumeMounts:
          # Monta o ConfigMap no caminho /config/filebrowser.json
          - mountPath: /config/filebrowser.json
            name: filebrowser-config
            subPath: filebrowser.json
          # Monta o arquivo filebrowser.db em /config/filebrowser.db
          - mountPath: /config/filebrowser.db
            name: filebrowser-db
            subPath: filebrowser.db
          # Monta o diretório de dados no caminho /srv
          - mountPath: /srv
            name: filebrowser-data
      volumes:
        # Volume para o ConfigMap (filebrowser.json)
        - name: filebrowser-config
          configMap:
            name: filebrowser-config
        # Volume PVC para o arquivo filebrowser.db
        - name: filebrowser-db
          persistentVolumeClaim:
            claimName: filebrowser-pvc
        # Volume PVC para os dados do File Browser
        - name: filebrowser-data
          persistentVolumeClaim:
            claimName: filebrowser-pvc
